git:
  depth: false

matrix:
  include:


###############################################################################
# OSX Release
###############################################################################

    - os: osx
      language: cpp
      cache: ccache
      osx_image: xcode10.1
      install:
        - export TZ=GMT-3
        - sudo systemsetup -gettimezone
        #- brew update
        #- brew install ccache
        #- export PATH="/usr/local/opt/ccache/libexec:$PATH"
        #- brew upgrade --ignore-pinned icu4c
        #- brew uninstall --ignore-dependencies sfcgal
        #- brew uninstall --ignore-dependencies cgal
        #- brew uninstall --ignore-dependencies node
        #- brew uninstall --ignore-dependencies postgresql
        #- brew uninstall --ignore-dependencies postgis
        - wget http://download.qt.io/official_releases/qt/5.15/5.15.0/single/qt-everywhere-src-5.15.0.tar.xz
        - tar -xf qt-everywhere-src-5.15.0.tar.xz
        - export QT5_INSTALL_DIR=$(pwd)/qt5-install
        - echo $QT5_INSTALL_DIR
      script:
        - mkdir qt5-build
        - cd qt5-build
        - ../qt-everywhere-src-5.15.0/configure  -release -opensource -static -prefix "$QT5_INSTALL_DIR" -silent -nomake examples -nomake tests -nomake tools -accessibility -no-sql-sqlite -qt-zlib -qt-libpng -qt-libjpeg -confirm-license -platform macx-clang
        - make -j1
        - make install
after_success:
    # deploy using ftp server
    - BUILDS_SERVER_PATH=${BUILD_SERVER}/files/QT5/$(date +%Y.%m.%d)
    - tar -cvzf qt-everywhere-src-5.15.0-static.tar.gz --directory=$QT5_INSTALL_DIR .
    - curl --retry 3 --ftp-create-dirs -T qt-everywhere-src-5.15.0-static.tar.gz $BUILDS_SERVER_PATH/
    - echo "Done"
